### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by dtod** [IUeDS/quickcheck#51]
This feels like an elementary question, but I'm setting up quickcheck behind a proxy, and when I try to test it, it keeps redirecting to https and looping on index.php

Accessing
http://127.0.0.1:8081/index.php/lticonfig

attempts a redirect to
https://127.0.0.1:8081/index.php/index.php/lticonfig

**Comment by mattmallon** [comment]
Hi David, you can set the `APP_ENV` value to `local` in your .env file to get around the middleware if you are working locally and testing the app. The app will redirect to https in production environments for security.

**Comment by dtod** [comment]
Thanks, Matt. I'd done that, but it didn't seem to change anything.

**Comment by mattmallon** [comment]
If it wasn't initially set to local, then changes to the .env file don't take effect unless you stop and restart the server process. If that doesn't work, you may also have to run `php artisan cache:clear` and `php artisan config:clear` if the .env values have been cached by Laravel.

**Comment by dtod** [comment]
Ah, I had started to wonder if it was a cache thing or something distinctive about rootless podman (still learning). I am not familiar with the various frameworks, but I had tried deleting bootstrap/cache/config.php after making a change to .env and it seemed to start working, but will use the commands you gave going forward.

Reproducing what worked here:

APP_ENV=local
APP_DEBUG=true
# Generate the key value using the following command: php artisan key:generate
APP_KEY=omitted
APP_URL=http://quickcheck

The apache proxy in front of it uses

ProxyPass "/quickcheck" "http://quickcheck"

The run command sets up quickcheck as a network alias is:

docker run -d -p 8081:80 --network mynetwork --network-alias=quickcheck -v .:/var/www/html:z -v /var/www/html/node_modules -v /var/www/html/vendor -v /var/www/html/public/assets/dist --name quickcheck quickcheck:1.0

and that seems to work.

**Comment by dtod** [comment]
actually, it looks like I'll need to update the APP_URL to the actual FQDN of the proxy url.

**Comment by dtod** [comment]
Got it installed, but now have an invalid OAuth signature. Probably due to proxy configuration.

**Comment by dtod** [comment]
Looks like Laravel doesn't really support sub-folder type urls as a base url, and that may be the underlying issue with my OAuth signature. Trying to address with x-forwarded-prefix but without success.
